version: '3.2'

services:

  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    mem_limit: 500m
    cpus: 0.5
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: empty
      MYSQL_DATABASE: oncall_local_dev
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  redis:
    image: redis
    mem_limit: 100m
    cpus: 0.1
    restart: always
    ports:
      - 6379:6379

  rabbit:
    image: "rabbitmq:3.7.15-management"
    mem_limit: 1000m
    cpus: 0.5
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - 15672:15672
      - 5672:5672

  mysql-to-create-grafana-db:
    image: mysql:5.7
    platform: linux/x86_64
    command: bash -c "mysql -h mysql -uroot -pempty -e 'CREATE DATABASE IF NOT EXISTS grafana CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;'"
    depends_on:
      mysql:
        condition: service_healthy

  grafana:
    image: "grafana/grafana:9.0.0-beta3"
    restart: always
    mem_limit: 500m
    cpus: 0.5
    environment:
      GF_DATABASE_TYPE: mysql
      GF_DATABASE_HOST: mysql
      GF_DATABASE_USER: root
      GF_DATABASE_PASSWORD: empty
      GF_SECURITY_ADMIN_USER: oncall
      GF_SECURITY_ADMIN_PASSWORD: oncall
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: grafana-oncall-app
    volumes:
      - ./grafana-plugin:/var/lib/grafana/plugins/grafana-plugin
      - grafana_plugin:/etc/grafana/provisioning/plugins/
    ports:
      - 3000:3000
    depends_on:
      mysql:
        condition: service_healthy

      grafana-plugin-provisioning:
        condition: service_completed_successfully


  grafana-plugin-provisioning:
    image: grafana/oncall
    volumes:
      - grafana_plugin:/plugins
    depends_on:
      mysql:
        condition: service_healthy

    command:
      - sh
      - '-c'
      - |
        rm /plugins/123.yml
        # Dirty hack to get the get the token from oncall backend
        # It runs the command, removes first three lines, extracts token and cleans it from any control characters
        # TODO: we need to add the command flag to return only the token
        # TODO: we need to supply the token as an env variable and insert it directly into oncall backend
        TOKEN=$$(python manage.py issue_invite_for_the_frontend --override | tail -n +4 | sed 's/.*Your invite token: \([^ ]*\).*/\1/' | sed 's/[^a-zA-Z0-9]//g')
        # Currently the only way to enable and provision the plugin in grafana is only through provisioning files in /etc/grafana/provisioning/plugins/
        # We want to keep the docker-compose distribution as slim as possible and consist only one docker-compose file
        # So we use a volume and this service to generate provisioning file and put it into grafana provisioning folder
        cat << EOF > /plugins/grafana-oncall-self-hosted.yml
        apiVersion: 1
        apps:
          - type: grafana-oncall-app
            jsonData:
              onCallApiUrl: http://host.docker.internal:8000
              grafanaUrl: http://grafana:3000
            secureJsonData:
              onCallInvitationToken: $$TOKEN
        EOF
        cat /plugins/grafana-oncall-self-hosted.yml
        echo Done

volumes:
  grafana_plugin: