name: helm-release

on:
  push:
    branches:
      - main
      - helm-release-tests

jobs:
  call-update-helm-repo:
    uses: grafana/helm-charts/.github/workflows/update-helm-repo.yaml@main
    with:
      charts_dir: helm/
      cr_configfile: helm/cr.yaml
      ct_configfile: helm/ct.yaml
    secrets:
      helm_repo_token: ${{ secrets.GH_BOT_ACCESS_TOKEN }}
      # See https://github.com/grafana/helm-charts/blob/main/INTERNAL.md about this key
      gpg_key_base64: ${{ secrets.HELM_SIGN_KEY_BASE64 }}
